### ISSUE TITLE
Auto Funnels and top user pathways

### ISSUE THREAD

**Issue by pranny** [octoai/gems#7]

**Comment by praateekmahajan** [comment]
To come on the same page

We track a user activity, which page he visits say page1 -> page 2 -> page 3
Store it in redis with a limit of say 60 seconds (assuming that session will last for 60 seconds)
Once the redis session expires, we push page1 -> page2 && page 2-> page3 on cassandra

enterprise_id |     p1     | direction |    p2     | weight
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
123                |  page1  |       1      |  page2 |    1

And everytime someone visits page2 from page1 we do a +1 on the weight

---

So now what I was wondering is, say a site has 10k pages, we can have 10k*10k rows like this.

It does not make sense for us to compute a markov model for every transition. It will be really expensive (computationally).

Instead according to me what a better approach would be to sort these transition wrt the weight, say we have a transition from p4 -> p7 a 100 times, p5 -> p9 couple of times. It will be a better solution to just compute the chain for such heavy transitions, instead of all other 9.9k transitions where weight is 1.

But the problem comes with cassandra. We can not query unless it's a primary key. And since the table mentioned above is a counter table, we can not add an index to it as well. 

So everytime now, we have to compute all the transitions from all the pages, and then call a .length/.count on client side. 

So what could be a better approach to build markov chains for the same?

I thought of two ideas,

1) Run a scheduler once a day, which traverse through all the rows, keep an array on client side just which gets the heaviest weights
2) Or setup the above table on another DBMS, say mongodb, as over there, all the query and everything can be done on backend, no restrictions on just using the primary keys to sort and search data. Since we are just storing funnel data, a point of failiure (which is anyway rare) will not be that big a deal, and it will not even have a lot of reads, just only when somebody asks to show the funnels. 

I prefer the second option, I believe it is going to be much more faster, and then we can use mongodb or whatever everytime for any such analytical purpose in the future.

**Comment by pranny** [comment]
So, the current system has a few issues
- Stores a backward, and forward counter for every page view. Increments both on every pageview. This causes n(n-1) db entries. Each pageview requires 2 db to FunnelTracker write
- Have to use shadow keys and catch events on expiry
- Ever increasing. There is no sense of time and even very old outliers can influence scores
- No way to find new pulse/funnels path

What we need to optimise is for:
- Faster retrieval
- Sense of recency
- Cheap Storage

Here are a few things we can do to optimise the architecture
- Use redis as a two way cache. Keep per user session path ( u, p1 -> p2 -> p3) as well as per hop (p1 -> p2, c) count. When a user (u) navigates from page (p1) to another page (p2), we update user session path (USP) in cache and also update the counter of that path (CoP). When a user lands directly to a page from the web (lets say from google results), then we just keep the entry in USP and no CoP is updated, (as this landing happens from a page which lies outside of our concerned universe). 
- USP Keys and CoP keys expire in different manner. USP keys are set to expire at the length of user session. (L minutes). The PoC keys expire at a "Event Window Threshold" of T minutes. Usually T > L. The idea behind using an Event Window Threshold is to filter out any path traversals that happened at a frequency less than threshold frequency (f) within time T.
  So, Imagine if a path traversal from P12 -> P34 happens 4 times every 3 hours. Depending on the nature of site, you may want to drop this from being adding towards final scores. And consider only those pages views that happen above this frequency (f=3) within the timeperiod (T=3_60_60). 
- This also introduces a sense of granularity and frequency of stats gathering. Typically a process would trigger every T time and catch the counters above filtering threshold

### Data Structure

We need to be able to find following things real quick
- Load of a node (= incoming frequency/ outgoing frequency)
- P(p1, p2)
- Top incoming nodes
- Top exiting nodes
- Top N most frequent paths

In order to find them, we need the following modules
- Node: A node module contains the information like counts of incoming connections, outgoing connections, listings of all incoming connection with weight, list of all outgoing connection etc.
- Graph: A graph module contains all nodes. It has methods to find top entry nodes, top outgoing nodes and so on.
  Internally we would require following tables
- Nodes List. Contains individual node specific information like
  - Node ID (p1)
  - Outgoing frequency (co)
  - Incoming frequency (ci)
  - Load (l) [Indexable, we need sorted]
- ForwardPath. This contains all the forward path details for a node. It contains
  - Start Node (p1)
  - Next Node (p2)
  - frequency (c)
  - sampling time (ts)
  - Probability (p) This field should also have indexing enabled on it.
- BackwardPath. This contains the the information about the presence or absence of any backward path. Conatins
  - Start Node (p1)
  - Previous Path (p0)

For updating we do following
- Update Counters Step. In this step we update the db frequencies with the counter values. This involves
  - Read current frequency for (p1,p2).
  - If current frequency < 1 or null
    - Increment the value of outgoing frequency (co) in Nodes List
  - Add counter values to current frequency
  - Write new frequency to db
  - Check in BackwardPath table if a path exists from (p2 to p1)
    - If exists, do nothing
    - If not exist, update the Incoming frequency by 1
  - Save the updated table rows
- Calculate next probability. In this step, we calculate the new probabilities of a path P(p1,p2)
  - For each updated node in step 1, do the following
  - Remove all the weights which have been updated more than B time ago. Typical value of B could be 7 days but even 30 days or more is also acceptable depending on how quickly the website changes its chains. This step keeps only the most popular ones in db.
  - Calculate the new probabilities for markov chains.

Now, how do we find the top G paths with a max path depth of D
- First we need to find entry nodes. These nodes would typically be the ones who have least load. Optionally, we could also take an explicit list of entry nodes. 
- Use markov chains for traversal and finding out the top G paths with a max depth of D.

There are open questions here:
- How should the markov chain transition matrix be stored? Cassandra is inefficient. Predictor uses Redis for storing such matrix. We can store it as an additional column in Nodes table.
- Exactly which algorithm should we choose for matrix traversal.

For more concurrency, we can possibly use Resque based workers for performing update and probabilities calculation.

This gives a general idea about doing the process at scale.

**Comment by pranny** [comment]
Closing this issue now. Relevent issues would be created in separate gems repo as and when this task is prioritized.
